<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="15p-yurym" failures="1" tests="1" name="test for XML Parser with invalid file 4" time="0.002" errors="0" timestamp="2023-11-13T13:48:21 CET">
  <testcase classname="parser.XMLParserTest" name="testInValidParser" time="0.002">
    <failure type="java.lang.AssertionError" message="Failed, corrupted file shown as valid expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Failed, corrupted file shown as valid expected [false] but found [true]
at parser.XMLParserTest.testInValidParser(XMLParserTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testInValidParser -->
  <testcase classname="parser.XMLParserTest" name="testValidParser" time="0.0">
    <ignored/>
  </testcase> <!-- testValidParser -->
</testsuite> <!-- test for XML Parser with invalid file 4 -->
